<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Kunals-MacBook-Pro.local" failures="1" tests="1" name="com.kunal.testcases.BankManagerLoginTest" time="0.347" errors="0" timestamp="2025-07-11T13:16:14 IST" skipped="0">
  <testcase classname="com.kunal.testcases.BankManagerLoginTest" name="loginAsBankmanager" time="0.347">
    <failure message="Failing testcase intentinally" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing testcase intentinally
at org.testng.Assert.fail(Assert.java:111)
at com.kunal.testcases.BankManagerLoginTest.loginAsBankmanager(BankManagerLoginTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Test case start: loginAsBankmanager
<br>Verification failure: expected [abc] but found [xyz]<br>
<a target="_blank" href=Fri_Jul_11_13_16_09_IST_2025error.jpg><img src=Fri_Jul_11_13_16_09_IST_2025error.jpg height=200 width=200></img></a>
<br>
<br>
Captuing screenshot..
Screenshot captured..
<a target="_blank" href=Fri_Jul_11_13_16_09_IST_2025error.jpg>Screenshot</a>
<br>
<br>
<a target="_blank" href=Fri_Jul_11_13_16_09_IST_2025error.jpg><img src =Fri_Jul_11_13_16_09_IST_2025error.jpg height=200 width=200></img></a>]]>
    </system-out>
  </testcase> <!-- loginAsBankmanager -->
  <system-out>
    <![CDATA[Test case start: loginAsBankmanager
<br>Verification failure: expected [abc] but found [xyz]<br>
<a target="_blank" href=Fri_Jul_11_13_16_09_IST_2025error.jpg><img src=Fri_Jul_11_13_16_09_IST_2025error.jpg height=200 width=200></img></a>
<br>
<br>
Captuing screenshot..
Screenshot captured..
<a target="_blank" href=Fri_Jul_11_13_16_09_IST_2025error.jpg>Screenshot</a>
<br>
<br>
<a target="_blank" href=Fri_Jul_11_13_16_09_IST_2025error.jpg><img src =Fri_Jul_11_13_16_09_IST_2025error.jpg height=200 width=200></img></a>
Test case start: addCustomer
Customer added successfully
Test case finished: addCustomer
Test case start: addCustomer
Customer added successfully
Test case finished: addCustomer
Test case start: openAccountTest
Account open successfully
Test case finished: openAccountTest]]>
  </system-out>
</testsuite> <!-- com.kunal.testcases.BankManagerLoginTest -->
